# Generated by Django 4.1.9 on 2023-06-25 22:11

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('PromotionID', models.CharField(max_length=255)),
                ('Marketplace', models.CharField(max_length=255)),
                ('PromotionsTitle', models.CharField(max_length=255)),
                ('PromotionsCoupon', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Promotions_Collection',
                'managed': False,
            },
        ),
    ]
