# Generated by Django 4.1.9 on 2023-07-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SingleProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products_Collection',
        ),
    ]
