# Generated by Django 4.1.9 on 2023-06-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='CustId',
            new_name='id',
        ),
    ]
