# Generated by Django 4.1.9 on 2023-06-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_favoriteproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteProducts',
        ),
    ]
