# Generated by Django 4.1.9 on 2023-06-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_delete_favoriteproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
