# Generated by Django 4.1.9 on 2023-07-04 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubCategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcat',
            table='New_Product_Collection',
        ),
    ]
