# Generated by Django 4.1.9 on 2023-07-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubCategories', '0002_alter_subcat_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcat',
            table='Products_Collection',
        ),
    ]
